### ISSUE TITLE
Comparisons are real booleans or 'True' & 'False' strings?

### ISSUE THREAD

**Issue by chuckwilliams37** [EdgeApp/biggystring#3]
Minor nit - the docs indicate that the comparison returns *could possibly* be strings. I went ahead and tested in code and they are indeed booleans. Might be worth clarifying in the docs.

**Comment by paullinator** [comment]
Thanks for the catch. Fixed in

https://github.com/EdgeApp/biggystring/commit/d9999052b011735ca3008b3099cb814405586b2d
